### ISSUE TITLE
Setting the pointer ring X position is not always correct

### ISSUE THREAD

**Issue by trungnt2910** [nor0x/Maui.ColorPicker#1]
From a default constructed `ColorPicker`, setting the `PointerRingPositionXUnits` property from code to `0.666` and the `PointerRingPositionYUnits` to `0` does not always point to the color "Blue". It sometimes gets off a little bit to the left and gives a lighter variant of blue.

Sometimes, this bug occurs:
![image](https://user-images.githubusercontent.com/57174311/190084680-a8e60eb6-5fe9-4567-9ec8-2ef42e9850b8.png)

Normally, this is the expected behavior:
![image](https://user-images.githubusercontent.com/57174311/190084854-fbcefed4-333f-4b15-8f9b-acfea45818ea.png)

The problem here is, the drawing and color determination relies on the `_lastTouchPoint`, which is relative to the `CanvasSize`. However, in some weird situations, `CanvasSize` can change, invalidating the coordinates of `_lastTouchPoint`.

See: https://github.com/nor0x/Maui.ColorPicker/blob/ce6fd9bb1813f0c82bb02a25d979c0a19864efe8/Maui.ColorPicker/ColorPicker.xaml.cs#L477-L479

**Comment by nor0x** [comment]
fixed by #8
