### ISSUE TITLE
Adding .UseSkiaSharp() to MauiProgram

### ISSUE THREAD

**Issue by mrijntjes** [nor0x/Maui.ColorPicker#11]
Hi, i'm now succesfully using Maui.ColorPicker but based on the readme of this repository i couldn't get it working. My .net 8.0 Maui app was keeping crashing after loading the view containing the ColorPicker. After a search on the internet there was an suggestion to add the .UseSkiaSharp() function to the MauiApp builder (in MauiProgram.cs). That solved for me the problem. It might be good to mention this in your readme, if users have not used SkiaSharp in their applications before. Thanks for this cool colorpicker by the way!

**Comment by nor0x** [comment]
thank you @mathiasrijntjes i have added the according steps to the readme.
