### ISSUE TITLE
License.md file is missing

### ISSUE THREAD

**Issue by ChristopherStephan** [nor0x/Maui.ColorPicker#13]
Hey, thanks for providing a color picker that works with .NET MAUI. We want to use it in our app. For legal reasons, it would be nice if you could add a license.md file to this repo. I noticed that package is distributed with the MIT license from the nuget gallery. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Best regards
Christopher

**Comment by nor0x** [comment]
there you go
https://github.com/nor0x/Maui.ColorPicker/blob/main/LICENSE

**Comment by ChristopherStephan** [comment]
Thank you very much!
