### ISSUE TITLE
Windows App crash, when the ColorPicker is on a XAML page

### ISSUE THREAD

**Issue by Grzesik** [nor0x/Maui.ColorPicker#18]
My .Net Maui app for Windows have worked with the ColorPicker very well till last month. I updated than Visual Studio and .Net Sdk to the newest version and I have a crash in the app, when I navigate to a page with the ColorPicker. It is enough to use the control on the page, without any binding and the app crashes. The app crashes so, that there is no exeption handling possible. 

Here are the relevat nuget packages:

<PackageReference Include="nor0x.Maui.ColorPicker" Version="2.0.3" />
<PackageReference Include="PrismShell.Maui" Version="1.0.3" />
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.92" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.92" />
<PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.8" />

**Comment by nor0x** [comment]
can you provide more details? have you tried the sample from the repo here or have your own repro which you can share?

**Comment by Grzesik** [comment]
The sample crashes directly when starting the app on Windows. If you delete the ColorPicker from the Xaml, it works fine.

[MauiApp1.zip](https://github.com/user-attachments/files/17446358/MauiApp1.zip)

**Comment by nor0x** [comment]
seems to be this issue
https://github.com/mono/SkiaSharp/issues/3034

i'm investigating

**Comment by Grzesik** [comment]
Thank you, it works now :-)
