### ISSUE TITLE
Support for .Net 8

### ISSUE THREAD

**Issue by TheresasAccount** [nor0x/Maui.ColorPicker#3]
Is .Net 8 support planned?

**Comment by MathijsWouters** [comment]
I am using it on .Net 8 and have no issues idk how i fixed it but it works

**Comment by nor0x** [comment]
it should work just fine with .NET 8. @TheresasAccount do you have anything specific in mind that's not working in a .NET 8 project?

**Comment by TheresasAccount** [comment]
@nor0x I am trying to put it into a .Net 8 class library and getting the following error.
Error	NU1202	Package nor0x.Maui.ColorPicker 1.0.1 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package nor0x.Maui.ColorPicker 1.0.1 supports:
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.4 (.NETCoreApp,Version=v6.0)
  - net6.0-maccatalyst15.4 (.NETCoreApp,Version=v6.0)
  - net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)	
  
The reason for putting it in the class library is because it needs to be unit testable and the platform specific apps both call the class library for all the logic and pages.

My mistake, I thought it was a .net version issue when it looks to be platform vs class library issue.

**Comment by TheresasAccount** [comment]
Fixed it by just adding it to the Maui application and having the page declared there instead of the class library.
