### ISSUE TITLE
Allow to set the initial color

### ISSUE THREAD

**Issue by Neralem** [nor0x/Maui.ColorPicker#4]
The PickedColor Property has no public setter. I can see no way to set the initial Color of the ColorPicker.

**Comment by taublast** [comment]
I have reused much code from this wonderful picker to create a totally drawn one few days ago.
https://github.com/taublast/DrawnUi.Maui/tree/main/src/samples/Sandbox/Views/Controls/ColorPicker
It has a setter etc. This was to say that i/we could port the drawn code back to this repo control, which wouldn't take much time, depends on what @nor0x intention is. 

https://github.com/nor0x/Maui.ColorPicker/assets/25801194/b0e8f788-8e9f-4c18-91ef-b11f43acf57e

**Comment by nor0x** [comment]
thanks for the info @taublast  and @Neralem 

this issue is now fixed and PickedColor has a public setter #8
