### ISSUE TITLE
Confusing fork

### ISSUE THREAD

**Issue by hansmbakker** [nor0x/Maui.ColorPicker#5]
There is a [fork of this package](https://github.com/trungnt2910/ColorPicker.Maui) with the result that there are now two very similar nuget packages available, where the forked package now has more downloads.

![image](https://github.com/nor0x/Maui.ColorPicker/assets/3463496/3786e74f-fba1-4022-a53d-099188623f37)

It's a bit confusing for users but it turns out that there are actually some improvements like a fix for #4. It's a pity that the improvements were done in a fork rather than contributing them back via PRs.

Would it be an idea to discuss with @trungnt2910 to have one merged repo and package?

**Comment by trungnt2910** [comment]
The reason I created a fork is because there are many technical details I do not agree with (API, build system, and so on). I decided to create an entirely incompatible fork to have the freedom to change stuff as I please.

**Comment by trungnt2910** [comment]
Merging the two repos would be quite a lot of work (both the original and my fork have been inactive for quite a while), unless you are OK with making a third, potentially more confusing, fork.

**Comment by nor0x** [comment]
2.0.0 includes the fixes for #4 and #1
https://github.com/nor0x/Maui.ColorPicker/pull/8
