### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by pfeiff190100** [nor0x/Maui.ColorPicker#9]
I am attempting to incorporate your library into my project, but I've encountered several issues and haven't been able to find a solution on my own.

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:Maui.ColorPicker;assembly=Maui.ColorPicker"
             x:Class="Luminote.MainPage"
             BackgroundColor="#121212">

    <StackLayout>
        <controls:ColorPicker
            x:Name="ColorPicker"
            ColorListDirection="Horizontal"
            GradientColorStyle="DarkToColorsToLightStyle"
            PickedColorChanged="ColorPicker_PickedColorChanged"
            PointerCircleBorderUnits="0.3"
            PointerCircleDiameterUnits="0.7">
        </controls:ColorPicker>
    </StackLayout>
</ContentPage>
```

When I add this code, I get the following errors:
- The property 'ColorListDirection' was not found in type 'ColorPicker'.
- The property 'GradientColorStyle' was not found in type 'ColorPicker'.
- The property 'PointerCircleBorderUnits' was not found in type 'ColorPicker'.
- The property 'PointerCircleDiameterUnits' was not found in type 'ColorPicker'.

Both your library and SkiaSharp are installed in my project.

What can i do to resolve my Issue?

**Comment by nor0x** [comment]
hey @pfeiff190100 👋

i noticed that during the migration somehow some wrong properties ended up in the first section of the readme.

The corrected code should be:

```xml
<controls:ColorPicker
            x:Name="ColorPicker"
            ColorFlowDirection="Horizontal"
            ColorSpectrumStyle="ShadeToHueStyle"
            PickedColorChanged="ColorPicker_PickedColorChanged"
            PointerRingBorderUnits="0.3"
            PointerRingDiameterUnits="0.7">
</controls:ColorPicker>
```

i will also fix the docs accordingly. You can also check the sample which has a working implementation

**Comment by nor0x** [comment]
see: 
8320b384253905467846e831104045c26b865357
